sudo: required
dist: trusty
language: node_js
node_js:
  - '4'
  - '5'
  - '6'
  - '7'
  - 'lts/*'
python:
  - "3.6"
before_install:
  - sudo add-apt-repository ppa:jonathonf/python-3.6
  - sudo apt-get update
  - sudo apt-get install python3.6
  - sudo apt-get -y install python3-pip python-dev
  - sudo pip3 install nose
  - python3 -V
  - pip3 -V
  - nosetests -V
script: make python-tests
