version: 2
jobs:
  build:
    docker:
      - image: circleci/node:7.10.1
    steps:
      - checkout
      - run: yarn install
      - run: npm link
      - run: add-reason -V
  test:
    docker:
      - image: circleci/python:3.4.3
    steps:
      - checkout
      - run: python -V
      - run: pip install node
      - run: pip -V
      - run: make test
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test
